import type { Metadata } from "next";
import localfont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const tusker = localfont({
  src: [{
    path:"../../public/fonts/TuskerGrotesk-2600Semibold.ttf",
    weight: "2600",
  },
],
variable: "--font-tusker",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${tusker.variable} font-sansmono`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
